### ISSUE TITLE
15这文件没有

### ISSUE THREAD

**Issue by d7185540** [yangzhi-1/yanglegeyang#1]
![image](https://user-images.githubusercontent.com/24641689/190356935-067def8b-c946-4375-b3f7-40b844abdb6a.png)

**Comment by syb024** [comment]
\WeChat Files\Applet

**Comment by d7185540** [comment]
找到了，原来是路径问题。

**Comment by QiHsMing** [comment]
> 找到了，原来是路径问题。

你们替换后有起作用了吗？
