### ISSUE TITLE
进入文件夹后看不到15

### ISSUE THREAD

**Issue by hd520131478** [yangzhi-1/yanglegeyang#2]

**Comment by haha5217** [comment]
+1

**Comment by syb024** [comment]
\WeChat Files\Applet

**Comment by QiHsMing** [comment]
> \WeChat Files\Applet

在这个目录下，替换压缩包，没有起作用 😢

**Comment by adufeng** [comment]
\WeChat Files\Applet\c970a9\ 下的没有15啊

**Comment by QiHsMing** [comment]
> _No description provided._

请问你们替换后有起作用了吗？
