### ISSUE TITLE
用不了了，微信版本V3.7.6.44

### ISSUE THREAD

**Issue by Rxxkles** [yangzhi-1/yanglegeyang#8]
![image](https://user-images.githubusercontent.com/37858725/190531584-edce5942-d245-4ce7-acf7-99cc4db1f100.png)

**Comment by Rxxkles** [comment]
问了其他同事，有的能用有的用不了

**Comment by yangzhi-1** [comment]
> 问了其他同事，有的能用有的用不了

# 我也是这个版本，还可以使用
![image](https://user-images.githubusercontent.com/98074256/190533407-1863cdfd-d7c1-4c17-829c-2f6b614ec1b8.png)
# 但是加载不完全
![image](https://user-images.githubusercontent.com/98074256/190533486-1749dd4c-1923-471f-888f-8b375159c01e.png)
![image](https://user-images.githubusercontent.com/98074256/190533597-f48a76fa-4ebf-4e78-8502-e4a0ac0a8dea.png)

**Comment by agamealion** [comment]
提示我清理缓存，老刘

**Comment by agamealion** [comment]
提示我清理缓存，老六行为

**Comment by echo-timeless** [comment]
> 提示我清理缓存，老六行为

那是没先进小程序再替换，我进了在替换就不会有提示，但是还是没效果

**Comment by JasonSunChen** [comment]
提醒我清理缓存了

**Comment by jiabuda** [comment]
> > 提示我清理缓存，老六行为
> 
> 那是没先进小程序再替换，我进了在替换就不会有提示，但是还是没效果

进了再替换的话，估计已经读入到内存里，你这样操作的话，我猜肯定是没有任何效果的

**Comment by Rxxkles** [comment]
[https://haiyong.site/post/ca43a9eb.html?continueFlag=1d5619bac7b76e8ede01bb02f9b7b83b](url)，刚看到这个方法，还没试呢服务器崩了，一会大家可以试试这个方法

**Comment by yangzhi-1** [comment]
> `https://haiyong.site/post/ca43a9eb.html?continueFlag=1d5619bac7b76e8ede01bb02f9b7b83b`，刚看到这个方法，还没试呢服务器崩了，一会大家可以试试这个方法

你这不是跟我的一样吗？

**Comment by Rxxkles** [comment]
> 

发错链接了，我更新一下😂

**Comment by Rxxkles** [comment]
> > `https://haiyong.site/post/ca43a9eb.html?continueFlag=1d5619bac7b76e8ede01bb02f9b7b83b`，刚看到这个方法，还没试呢服务器崩了，一会大家可以试试这个方法
> 
> 你这不是跟我的一样吗？
发错链接了，我更新一下`https://haiyong.site/post/e44ad8a0.html`

**Comment by yangzhi-1** [comment]
> 

我刚才找了一下，不同用户那个文件夹是不一样的，还有，建议你发的链接不要有QQ群之类的，会让我觉得你在引流

**Comment by yangzhi-1** [comment]
> > > `https://haiyong.site/post/ca43a9eb.html?continueFlag=1d5619bac7b76e8ede01bb02f9b7b83b`，刚看到这个方法，还没试呢服务器崩了，一会大家可以试试这个方法
> > 
> > 
> > 你这不是跟我的一样吗？
> > > 发错链接了，我更新一下`https://haiyong.site/post/e44ad8a0.html`

我刚才找了一下，不同用户那个文件夹是不一样的，还有，建议你发的链接不要有QQ群之类的，会让我觉得你在引流
